learn_metal/01-primitive/01-primitive.odin, learn_metal/02-argbuffers/02-argbuffers.odin, learn_metal/03-animation/03-animation.odin, learn_metal/04-instancing/04-instancing.odin, learn_metal/05-perspective/05-perspective.odin, learn_metal/06-lighting/06-lighting.odin, learn_metal/07-texturing/07-texturing.odin, learn_metal/08-compute/08-compute.odin, learn_metal/09-compute-to-render/09-compute-to-render.odin
updating examples to reflect a recent change to `newTexture` and `newRenderPipeline`
=> Fix metal selector names in learn_metal examples

math/noise/draw_texture/noise.odin
This won't work unless https://github.com/odin-lang/Odin/pull/1777 is also merged.
In addition to adding `glfw.WindowHint(glfw.OPENGL_FORWARD_COMPAT, glfw.TRUE)` line for example to work in macOS, this lowers the OpenGL version to 4.1 for the same reason. It doesn't seem like 4.5 is strictly required here.
Some trailing spaces are trimmed. And human readable error logging is added.
=> Make math/noise example to work in macOS

sdl2/opengl/sdl2_opengl_demo.odin
The example fails to run on my computer without these changes. I realize this is platform-dependent problem, but I believe these changes should be generally more inclusive.
=> Fix SDL2 OpenGL example

sdl2/chase_in_space/chase_in_space.odin
Fix since the sdl2 bindings changed to return a `b32`
=> Fix `for sdl2.PollEvent(&event)` for new sdl2 bindings

by_example/read_console_input/read_console_input.odin
line 9 had a io.read instead of os.read, also the read function expects 2 arguments so i put os.stdin. Also the returned error should not be compared against nil because it is a int32 type.
=> os.read instead of io.read

raylib/game_of_life/game_of_life.odin
There were of bounds errors if the mouse was clicked and dragged out of window at top left and bottom edge. Behavior now in-line with count_neighbors (double modulo operator to wrap coordinates)
=> Fixed out of bounds errors during painting (game_of_life)

.github/workflows/check.yml, json/odin_info/odin_info.odin
=> How to write odin info as json

.github/workflows/check.yml, .gitignore, learn_metal/02-argbuffers-no-sdl/02-argbuffers-no-sdl.odin, learn_metal/02-argbuffers/02-argbuffers.odin
=> Cocoa Metal example (no SDL).

raylib/game_of_life/game_of_life.odin
Updated comments so they follow the same style. Also, removed all the double-spaces, doubled words, etc.
=> Fix typos and style in Examples

.github/workflows/check.yml, directx/d3d12_triangle_sdl2/d3d12_triangle_sdl.odin
Side note:
I know the d3d11 example is in `sdl` folder. I'll move that one to the directx folder in a separate PR after this one has been merged. It makes more sense that d3d examples live in the directx folder. The SDL stuff is just for opening the window; the meat of those examples is d3d.
=> DirectX 12 triangle (SDL2 window)

dir_info/main.odin
=> Simplified dir_info example

metal/learn_metal/README.md
Closes #93 
This is only a spelling fix, these checklist items were already all done.
=> Fix learn Metal README links

win32/open_window/main.odin
This fixes an issue where the cursor for win32 windows shows a spinner cursor and a possibility where the drag arrow might become persistent.
- [x ] This example has been added to `.github/workflows/check.yml` (for automatic testing)
- [ x] This example compiles cleanly with flags `-vet -strict-style -vet-tabs -disallow-do -warnings-as-errors`
- [ x] This example follows the `core` naming convention: https://github.com/odin-lang/Odin/wiki/Naming-Convention (exception can be made for ports of examples that need to match 1:1 to the original source).
- [x ] By submitting, I understand that this example is made available under these licenses: [Public Domain](https://unlicense.org) and [Odin's BSD-3 license](https://github.com/odin-lang/Odin/blob/master/LICENSE). …
=> add explicit cursor assignment in win32 window example

.github/workflows/check.yml, thread/sync_mutex/thread_sync_mutex.odin, thread/synchronization/thread_synchronization.odin
=> Adding non-trivial Threading example with sync primitive usage.

.github/workflows/check.yml, simd/approaches/main.odin, simd/basic-sum/main.odin, simd/motion/main.odin
This example is intended to show various steps of SIMD-ification ranging from
scalar AoS code to vectorized SoA code, and some approaches to using SIMD with
varying impacts on data layout.
=> SIMD Example: Approaches

console/raw_console/main.odin
Backspace and newline characters weren't being recognized
=> Small bugfix in windows raw_console

code_generation/generate_image_info/generate_image_info.odin
otherwise the generated file mode will be 0x000.
=> Update generate_image_info.odin to add file mode

.github/workflows/check.yml, net/udp_echo_server/README.md, net/udp_echo_server/client/client.odin, net/udp_echo_server/server/server.odin
=> Add UDP echo server example

.github/workflows/check.yml, raylib/ports/core/core_basic_window.odin
Added `core-basic-window` raylib example which is based on [core_basic_window.c](https://www.raylib.com/examples/core/loader.html?name=core_basic_window)
=> Added core-basic-window raylib example

win32/game_of_life/game_of_life.odin
Fixed compilation errors for `win32/game_of_life` example. 
=> Fixed compilation errors
